<?php
$login_customer = $block->getLayout()->createBlock('Magento\Customer\Block\Account\Customer');
$welcomeMessage = $block->getWelcome();
?>

<div class="header-container header-style-6">
    <div class="header-top clearfix">
        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-md-5">
                    <div class="top-left-content clearfix">
                        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header-social')->toHtml(); ?>
                    </div>
                </div>

                <div class="col-lg-7 col-md-12 col-sm-12">
                    <div class="setting-store">
                        <?php echo $block->getChildHtml('language-header'); ?>
                        <?php echo $block->getChildHtml('currency-header'); ?>
                    </div>

                    <div class="customer-action">
                        <?php echo $block->getChildHtml('header.links'); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="header-middle ontop-element">
        <div class="container">
            <div class="middle-content">
                <div class="row">
                    <div class="col-lg-3 col-md-3">
                        <?php echo $block->getChildHtml('logo_theme'); ?>
                    </div>

                    <div class="col-lg-9 col-md-9">
                        <div class="middle-right-content">
                            <div class="header-navigation">
                                <div class="desktop-navigation clearfix">
                                    <?php
                                    if ($_config->getGeneral('menu_style') == 'megamenu') {
                                        echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('horizontal-megamenu')->toHtml();
                                    } else {
                                        echo $block->getChildHtml('navigation.horizontal.css');
                                    } ?>
                                </div>

                                <div class="navigation-mobile-container">
                                    <?php echo $block->getChildHtml('navigation.mobile'); ?>
                                </div>
                            </div>

                            <?php echo $block->getChildHtml('cart-header'); ?>
                            <?php echo $block->getChildHtml('search-header-pro'); ?>

                            <a id="search-btn" class="search-btn" title="<?php echo __('Search'); ?>"
                               href="javascript:void(0);"><span><?php echo __('Search'); ?></span></a>

                            <script>
                                require([
                                    'jquery'
                                ], function ($) {
                                    $("#search-btn").click(function () {
                                        $('body').toggleClass('show-search');
                                        $(this).toggleClass('active');
                                    });
                                });
                            </script>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


