<?php
$login_customer = $block->getLayout()->createBlock('Magento\Customer\Block\Account\Customer');
$welcomeMessage = $block->getWelcome();
?>

<div class="header-container header-style-1">
    <div class="header-top clearfix">
        <div class="container">
            <div class="row">
                <div class="col-lg-7 col-md-5 action-left">
                    <div class="top-left-content clearfix">
                        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header-social')->toHtml(); ?>
                        <?php echo $block->getChildHtml('language-header'); ?>
                        <?php echo $block->getChildHtml('currency-header'); ?>
                    </div>
                </div>

                <div class="col-lg-5 col-md-7 action-right">
                    <div class="customer-action">
                        <?php echo $block->getChildHtml('header.links'); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="header-middle">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <?php echo $block->getChildHtml('logo_theme'); ?>
                </div>

                <div class="col-lg-9">
                    <div class="middle-right">
                        <div class="middle-right-container">
                            <?php echo $block->getChildHtml('search-header-pro'); ?>

                            <div class="wishlist-header">
                                <a href="<?php echo $this->getUrl('wishlist') ?>"
                                   title="<?php echo __('My Wishlist') ?>">
                                    <span><?php echo __('My Wishlist') ?></span>
                                </a>
                            </div>

                            <?php echo $block->getChildHtml('cart-header'); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="header-bottom ontop-element">
        <div class="container">
            <div class="header-navigation">
                <div class="desktop-navigation">
                    <div class="row">
                        <div class="col-lg-3">
                            <div class="vertical-megamenu">
                                <?php
                                if ($_config->getGeneral('menu_style') == 'megamenu') {
                                    echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('vertical-megamenu')->toHtml();
                                } else {
                                    echo $block->getChildHtml('navigation-header');
                                } ?>
                            </div>
                        </div>

                        <div class="col-lg-9">
                            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('horizontal-megamenu')->toHtml(); ?>
                        </div>
                    </div>
                </div>

                <div class="navigation-mobile-container">
                    <?php echo $block->getChildHtml('navigation.mobile'); ?>
                </div>
            </div>

        </div>
    </div>
</div>


