<?php
/*------------------------------------------------------------------------
# SM Filter Products - Version 1.0.0
# Copyright (c) 2016 YouTech Company. All Rights Reserved.
# @license - Copyrighted Commercial Software
# Author: YouTech Company
# Websites: http://www.magentech.com
-------------------------------------------------------------------------*/

use Magento\Framework\App\Action\Action;

?>

<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper            = $this->helper('Magento\Catalog\Helper\Output');
$_config            = $this->helper('Sm\Autostore\Helper\Data');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?php /* @escapeNotVerified */
            echo __('We can\'t find products matching the selection.') ?></div>
    </div>
<?php else: ?>
    <?php
    $viewMode        = 'grid';
    $image           = 'category_page_grid_big3';
    $showDescription = true;
    $templateType    = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $showWishlist    = true;
    $showCompare     = true;
    $showCart        = true;
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos    = $block->getPositioned();
    $tag_id = "sm_filterproducts_" . time() . rand() . "";
    ?>

    <?php
    if ($this->_getConfig('product_source') == 'countdown_products') {
        $dateTo = $this->_getConfig('date_to', '');
        ?>
        <div class="deals-countdown" data-timer="<?php echo date("Y/m/d H:i:s", strtotime($dateTo)); ?>">
            <div class="deals-time time-day">
                <div class="num-time"></div>
                <div class="title-time"></div>
            </div>
            <div class="deals-time time-hours">
                <div class="num-time"></div>
                <div class="title-time"></div>
            </div>
            <div class="deals-time time-mins">
                <div class="num-time"></div>
                <div class="title-time"></div>
            </div>
            <div class="deals-time time-secs">
                <div class="num-time"></div>
                <div class="title-time"></div>
            </div>
        </div>
    <?php } ?>

    <?php $iterator = 1; ?>
    <div id="<?php echo $tag_id; ?>" class="owl-carousel owl-theme">
        <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
        <?php foreach ($_productCollection as $_product): ?>
            <?= /* @escapeNotVerified */
            ($iterator++ == 1) ? '<div class="item product product-item">' : '</div><div class="item product product-item">' ?>
            <div class="product-item-info" data-container="product-<?= /* @escapeNotVerified */
            $viewMode ?>">
                <?php
                $productImage = $block->getImage($_product, $image);
                if ($pos != null) {
                    $position = ' style="left:' . $productImage->getWidth() . 'px;'
                        . 'top:' . $productImage->getHeight() . 'px;"';
                }
                ?>
                <?php // Product Image ?>
                <div class="product-item-image">
                    <a href="<?= /* @escapeNotVerified */
                    $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?= $productImage->toHtml() ?>
                    </a>
                </div>

                <div class="product details product-item-details">
                    <?php
                    $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                    ?>
                    <strong class="product name product-item-name">
                        <a class="product-item-link"
                           href="<?= /* @escapeNotVerified */
                           $_product->getProductUrl() ?>">
                            <?= /* @escapeNotVerified */
                            $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                        </a>
                    </strong>
                    <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                    <?= /* @escapeNotVerified */
                    $block->getProductPrice($_product) ?>
                    <?= $block->getProductDetailsHtml($_product) ?>

                    <?php if ($showDescription): ?>
                        <div class="product description product-item-description">
                            <?php
                            $content    = $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description');
                            $short_text = strip_tags($content);
                            echo substr($short_text, 0, 148) . '...';
                            ?>
                        </div>
                    <?php endif; ?>

                    <?php
                    if ((int)$this->_getConfig('display_countdown') && !empty($_product->getSpecialPrice()) && !empty($_product->getSpecialToDate())) {
                        $specialToDate = $_product->getSpecialToDate();
                        ?>
                        <div class="deals-countdown clearfix"
                             data-timer="<?php echo date("Y/m/d H:i:s", strtotime($specialToDate)); ?>">
                            <div class="deals-time time-day">
                                <div class="num-time"></div>
                                <div class="title-time"></div>
                            </div>
                            <div class="deals-time time-hours">
                                <div class="num-time"></div>
                                <div class="title-time"></div>
                            </div>
                            <div class="deals-time time-mins">
                                <div class="num-time"></div>
                                <div class="title-time"></div>
                            </div>
                            <div class="deals-time time-secs">
                                <div class="num-time"></div>
                                <div class="title-time"></div>
                            </div>
                        </div>
                    <?php } ?>

                    <div class="product-item-inner">
                        <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                            <?php if ($_config->getAdvanced('show_addtocart_button')) { ?>
                                <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form"
                                              data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
                                              action="<?= /* @NoEscape */
                                              $postParams['action'] ?>" method="post">
                                            <input type="hidden" name="product" value="<?= /* @escapeNotVerified */
                                            $postParams['data']['product'] ?>">
                                            <input type="hidden" name="<?= /* @escapeNotVerified */
                                            Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */
                                            $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                    title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                    class="action tocart primary">
												<span><?= /* @escapeNotVerified */
                                                    __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->isAvailable()): ?>
                                            <div class="stock available"><span><?= /* @escapeNotVerified */
                                                    __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?= /* @escapeNotVerified */
                                                    __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                            <?php } ?>

                            <div class="actions-secondary">
                                <?php if ($_config->getAdvanced('show_wishlist_button')) { ?>
                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                        <a href="#" class="action towishlist"
                                           title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                           aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                           data-post='<?php /* @escapeNotVerified */
                                           echo $block->getAddToWishlistParams($_product); ?>'
                                           data-action="add-to-wishlist" role="button">
											<span><?php /* @escapeNotVerified */
                                                echo __('Add to Wish List') ?></span>
                                        </a>
                                    <?php endif; ?>
                                <?php } ?>

                                <?php if ($_config->getAdvanced('show_compare_button')) { ?>
                                    <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                    <a href="#" class="action tocompare"
                                       title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                       aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                       data-post='<?php /* @escapeNotVerified */
                                       echo $compareHelper->getPostDataParams($_product); ?>' role="button">
										<span><?php /* @escapeNotVerified */
                                            echo __('Add to Compare') ?></span>
                                    </a>
                                <?php } ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <?= ($iterator == count($_productCollection) + 1) ? '</div>' : '' ?>
        <?php endforeach; ?>
    </div>


    <script>
        require([
            'jquery'
        ], function ($) {
            var $element = $('#<?php echo $tag_id ?>');

            function CountDown(date, id) {
                dateNow = new Date();
                amount = date.getTime() - dateNow.getTime();
                delete dateNow;
                if (amount < 0) {
                    id.html("Now!");
                } else {
                    days = 0;
                    hours = 0;
                    mins = 0;
                    secs = 0;
                    out = "";
                    amount = Math.floor(amount / 1000);
                    days = Math.floor(amount / 86400);
                    amount = amount % 86400;
                    hours = Math.floor(amount / 3600);
                    amount = amount % 3600;
                    mins = Math.floor(amount / 60);
                    amount = amount % 60;
                    secs = Math.floor(amount);
                    $(".time-day .num-time", id).text(days);
                    $(".time-day .title-time", id).text(((days <= 1) ? "<?php echo __('Day')?>" : "<?php echo __('Days')?>"));
                    $(".time-hours .num-time", id).text(hours);
                    $(".time-hours .title-time", id).text(((hours <= 1) ? "<?php echo __('Hrs')?>" : "<?php echo __('Hrs')?>"));
                    $(".time-mins .num-time", id).text(mins);
                    $(".time-mins .title-time", id).text(((mins <= 1) ? "<?php echo __('Min')?>" : "<?php echo __('Mins')?>"));
                    $(".time-secs .num-time", id).text(secs);
                    $(".time-secs .title-time", id).text(((secs <= 1) ? "<?php echo __('Sec')?>" : "<?php echo __('Secs')?>"));
                    setTimeout(function () {
                        CountDown(date, id)
                    }, 1000);
                }
            }

            $(".deals-countdown", $element).each(function () {
                var timer = $(this).data('timer');
                var data = new Date(timer);
                CountDown(data, $(this));
            });
        });
    </script>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }

        
        
        </script>
    <?php endif; ?>
<?php endif; ?>
