<?php
/**
 * Copyright © 2016 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog recent posts widget
 *
 * @var $block \Magefan\Blog\Block\Widget\Recent
 */
?>

<?php
$_postCollection   = $block->getPostCollection();
$_config           = $this->helper('Sm\Autostore\Helper\Data');
$enableLadyLoading = $_config->getAdvanced('enable_ladyloading');
$mediaSrc          = $_config->getMediaUrl();
if ($enableLadyLoading) {
    $imgClass = 'lazyload';
} else {
    $imgClass = '';
}
?>
<?php if ($_postCollection->count()) { ?>
    <div class="owl-carousel owl-theme">
        <?php foreach ($_postCollection as $_post) { ?>
            <?php
            $_postUrl  = $_post->getPostUrl();
            $_postName = $block->escapeHtml($_post->getTitle(), null, true);
            ?>
            <div class="item item-post">
                <div class="image-blog">
                    <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
                        <a href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
                            <img class="<?php echo $imgClass; ?>"

                                <?php if ($enableLadyLoading) { ?>
                                    src="<?php echo $mediaSrc . 'lazyloading/blank.png'; ?>"
                                    data-src="<?php echo $featuredImage ?>"
                                <?php } else { ?>
                                    src="<?php echo $featuredImage ?>"
                                <?php } ?>
                                 width="1"
                                 height="1"
                                 alt="<?php echo $_postName ?>"
                            />
                        </a>
                    <?php } else { ?>
                        <a title="<?php echo $_postName; ?>" href="<?php echo $_postUrl ?>">
                            <img class="owl-lazy" src="<?php /* @escapeNotVerified */
                            echo $block->getViewFileUrl('images/post/no_image.jpg') ?>" alt="<?php echo $_postName ?>"/>
                        </a>
                    <?php } ?>
                </div>

                <div class="info-blog">
                    <div class="date-post">
                        <?php echo $_post->getPublishDate('Y-m-d'); ?>
                    </div>

                    <h4 class="postTitle">
                        <a class="post-item-link" href="<?php echo $_postUrl ?>">
                            <?php echo $_postName; ?>
                        </a>
                    </h4>

                    <div class="read-more">
                        <a href="<?php echo $_postUrl ?>"><?php echo __('Read More') ?></a>
                    </div>
                </div>
            </div>

        <?php } ?>
    </div>
<?php } ?>