<div class="footer-top">
    <div class="container">
        <div class="social-newsletter">
            <div class="row">
                <div class="col-lg-4">
                    {{block class="Magento\Framework\View\Element\Template"
                    template="Magento_Theme::html/social.phtml"}}
                </div>

                <div class="col-lg-8">
                    <div class="footer-newsletter">
                        <p class="title-newsletter">Sign Up For Newsletter & get <span>25% Off</span> first order</p>
                        {{block class="Magento\Newsletter\Block\Subscribe" template="subscribe-footer.phtml"}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="footer-middle">
    <div class="container">
        <div class="row">
            <div class="col-xl-4 col-lg-3">
                <div class="block-footer block-contact-footer">
                    <div class="title-footer">Contact Us</div>

                    <div class="content-footer content-about">
                        <ul>
                            <li class="address">
                                5611 Wellington Road, Suite 115, Gainesville,VA 20155<br/>Los Angeles city, USA.
                            </li>

                            <li class="phone">
                                888 9344 6000 - 888 1234 6789
                            </li>

                            <li class="email">
                                autostore@magentech.com
                            </li>

                            <li class="time-work">
                                7 Days a week from 10-00 am to 6-00 pm
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="col-lg-2">
                <div class="block-footer">
                    <div class="title-footer">Store Location</div>

                    <div class="content-footer">
                        <ul>
                            <li>
                                <a href="#">Los Angeles - USA</a>
                            </li>

                            <li>
                                <a href="#">New York - USA</a>
                            </li>

                            <li>
                                <a href="#">California - USA</a>
                            </li>

                            <li>
                                <a href="#">Bangkok - Thailand</a>
                            </li>

                            <li>
                                <a href="#">Paris - France</a>
                            </li>

                            <li>
                                <a href="#">London - England</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="col-lg-2">
                <div class="block-footer">
                    <div class="title-footer">Customer Service</div>

                    <div class="content-footer">
                        <ul>
                            <li>
                                <a href="#">Customer Service</a>
                            </li>

                            <li>
                                <a href="#">Shipping & Returns</a>
                            </li>

                            <li>
                                <a href="#">Track Your Order</a>
                            </li>

                            <li>
                                <a href="#">Help Center</a>
                            </li>

                            <li>
                                <a href="#">Store Location</a>
                            </li>

                            <li>
                                <a href="#">Customer Feedback</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>


            <div class="col-xl-2 col-lg-3">
                <div class="block-footer">
                    <div class="title-footer">Information</div>

                    <div class="content-footer">
                        <ul>
                            <li>
                                <a href="#">Caps & Hats</a>
                            </li>

                            <li>
                                <a href="#">Hoodies & Sweatshirts</a>
                            </li>

                            <li>
                                <a href="#">Jacket & Coats</a>
                            </li>

                            <li>
                                <a href="#">Jumpers & Cardigans</a>
                            </li>

                            <li>
                                <a href="#">Shoes, Boots & Trainers</a>
                            </li>

                            <li>
                                <a href="#">Underwear & Socks</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="col-xl-2 col-lg-3">
                <div class="block-footer">
                    <div class="title-footer">Information</div>

                    <div class="content-footer">
                        <ul>
                            <li>
                                <a href="#">Caps & Hats</a>
                            </li>

                            <li>
                                <a href="#">Hoodies & Sweatshirts</a>
                            </li>

                            <li>
                                <a href="#">Jacket & Coats</a>
                            </li>

                            <li>
                                <a href="#">Jumpers & Cardigans</a>
                            </li>

                            <li>
                                <a href="#">Shoes, Boots & Trainers</a>
                            </li>

                            <li>
                                <a href="#">Underwear & Socks</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>