<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @see \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>

<nav class="navigation" role="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <li class="home-item level0 level-top ui-menu-item">
            <a href="<?php echo $this->getUrl('') ?>" class="level-top ui-corner-all">
                <span><?php echo __('Home') ?></span>
            </a>
        </li>

        <?php /* @escapeNotVerified */
        echo $_menu; ?>
    </ul>
</nav>